<a href="https://colab.research.google.com/github/adipurnamk/Belajar-Pengembangan-Machine-Learning/blob/master/Binary_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

dataset [Kaggle](https://www.kaggle.com/joshmcadams/oranges-vs-grapefruit)

In [1]:
# melakukan ekstraksi pada file zip
import zipfile,os
local_zip = '/content/451798_880586_bundle_archive.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content')
zip_ref.close()

os.listdir('/content')

['.config', 'citrus.csv', '451798_880586_bundle_archive.zip', 'sample_data']

In [2]:
import pandas as pd
df = pd.read_csv('/content/citrus.csv')
df

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [4]:
df.head(10000)

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [5]:
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1
df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


name  diameter  weight  red  green  blue
0       0      2.96   86.76  172     85     2
1       0      3.91   88.05  166     78     3
2       0      4.42   95.17  156     81     2
3       0      4.47   95.60  163     81     4
4       0      4.48   95.76  161     72     9
...   ...       ...     ...  ...    ...   ...
9995    1     15.35  253.89  149     77    20
9996    1     15.41  254.67  148     68     7
9997    1     15.59  256.50  168     82    20
9998    1     15.92  260.14  142     72    11
9999    1     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [6]:
dataset = df.values
dataset

array([[0, 2.96, 86.76, 172, 85, 2],
       [0, 3.91, 88.05, 166, 78, 3],
       [0, 4.42, 95.17, 156, 81, 2],
       ...,
       [1, 15.59, 256.5, 168, 82, 20],
       [1, 15.92, 260.14, 142, 72, 11],
       [1, 16.45, 261.51, 152, 74, 2]], dtype=object)

In [7]:
# pilih 4 kolom terakhir sebagai atribut
X = dataset[:,1:6]
# bilangan sebelum koma untuk memilih baris pada dataframe
# bilangan setelah koma untuk memilih kolom pada dataframe

In [8]:
y = dataset[:,0]

In [9]:
# Normalization
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [10]:
# pisahkan data training dan testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)
Y_train = Y_train.astype(float)

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
model = Sequential([    
                    Dense(32, activation='relu', input_shape=(5,)),    
                    Dense(32, activation='relu'),    
                    Dense(1, activation='sigmoid'),])

In [13]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [14]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
219/219 [==============================] - 0s 1ms/step - loss: 0.6871 - accuracy: 0.5721
Epoch 2/100
219/219 [==============================] - 0s 1ms/step - loss: 0.6592 - accuracy: 0.8711
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.6254 - accuracy: 0.9127
Epoch 4/100
219/219 [==============================] - 0s 1ms/step - loss: 0.5699 - accuracy: 0.9214
Epoch 5/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4885 - accuracy: 0.9227
Epoch 6/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3951 - accuracy: 0.9254
Epoch 7/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.9241
Epoch 8/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2612 - accuracy: 0.9261
Epoch 9/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2290 - accuracy: 0.9260
Epoch 10/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2098 - accura

In [15]:
print(type(Y_train))
Y_train

<class 'numpy.ndarray'>


array([0., 0., 1., ..., 1., 0., 0.])

In [16]:
print(type(X_train))
X_train

<class 'numpy.ndarray'>


array([[0.44106746, 0.41505007, 0.76623377, 0.61176471, 0.05555556],
       [0.4595997 , 0.43771102, 0.46753247, 0.76470588, 0.2037037 ],
       [0.55596738, 0.54094421, 0.36363636, 0.24705882, 0.07407407],
       ...,
       [0.64195701, 0.64715308, 0.51948052, 0.34117647, 0.03703704],
       [0.53817643, 0.52600858, 0.50649351, 0.68235294, 0.        ],
       [0.21349148, 0.16143062, 0.58441558, 0.65882353, 0.        ]])

In [18]:
Y_test = Y_test.astype(float)

model.evaluate(X_test, Y_test)
# elemen pertama adalah loss dan elemen kedua adalah akurasi

94/94 [==============================] - 0s 912us/step - loss: 0.1838 - accuracy: 0.9280


[0.18375921249389648, 0.9279999732971191]